### ISSUE TITLE
More than one instance of overloaded function Watchdog::watch matches the argument list

### ISSUE THREAD

**Issue by ellion** [simongeilfus/Watchdog#2]
Hi there,

I'm trying to use Watchdog with Cinder, running Visual Studio Express 2013. Sadly, I can't get around the error mentioned in the title, even when simply trying to use your example call:

wd::watch( "shaders/lighting.*", []( const fs::path &path ){
    // do something
} );

Intellisense says it could mean a call to both variants of watch(). Do you have any idea what is going on here?

Thanks in advance,
Daniel

**Comment by simongeilfus** [comment]
Hi Daniel,

Thanks for reporting the issue, there's a conversation about it going on cinder forum (
https://forum.libcinder.org/topic/watchdog#23286000002228083) and it's probably a better idea to address it here.

I just did a commit with a temporary fix, let me know if that works for you!

**Comment by ellion** [comment]
Perfect, works like a charm!

Thank you very much for your quick response and your overall work here!
